name: 小米Miloco
slug: miloco
description: Xiaomi Local Copilot 以米家摄像机为视觉信息来源，以自研大模型为核心，打通全屋 IoT 设备。基于大模型的开发范式，让用户能够以自然语言定义家庭的各种需求和规则，实现更广泛、更具创意的智能联动。
version: 0.1.8
url: https://github.com/oopuuu/xiaomi-miloco
webui: https://[HOST]:[PORT:28800]
panel_icon: mdi:webcam
ingress: false
init: false
arch:
  - amd64
  - aarch64
host_network: true
ports:
  28800/tcp: 28800
map:
  - addon_config:rw
  - homeassistant_config:rw
  - share
build_args:
  - BUILD_DATETIME
schema:
  envs:
    - match(^[A-Z0-9_]+=.*$)
options:
  envs:
    - BACKEND_PORT=28800
    - BACKEND_LOG_LEVEL=warning
    - TZ=Asia/Shanghai
