name: 小米Miloco
slug: miloco
description: Xiaomi Local Copilot 修改版，主要增加了内置rtsp推流。
version: 0.1.9b
url: https://github.com/oopuuu/xiaomi-miloco
webui: https://[HOST]:[PORT:28800]
panel_icon: mdi:webcam
ingress: false
init: false
arch:
  - amd64
  - aarch64
host_network: true

# [关键修改 1] 开启视频设备访问权限
# 没有这一行，容器内找不到 /dev/dri，硬件转码必挂
video: true

ports:
  28800/tcp: 28800
  36674/tcp: 36674
map:
  - addon_config:rw
  - homeassistant_config:rw
  - share
build_args:
  - BUILD_DATETIME
schema:
  envs:
    - match(^[A-Z0-9_]+=.*$)
options:
  envs:
    - BACKEND_PORT=28800
    - RTSP_PORT=36674
    - LITE_MODE=true
    - BACKEND_LOG_LEVEL=warning
    - TZ=Asia/Shanghai
    # [关键修改 2] 添加硬件加速开关，默认为 intel (适配你的 N5105)
    # 可选值: cpu, intel, nvidia, mac, rpi
    - MILOCO_HW_ACCEL=intel
    # 指定渲染设备，通常 N5105 核显就是这个
    - MILOCO_HW_DEVICE=/dev/dri/renderD128
